language: python
python:
   - 3.5
   - 3.6
sudo: required
before_install: sudo pip install -r requirements.txt
# command to install dependencies
#install: "pip install -r requirements.txt"
# command to run tests
script:
  - python run.py
